// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auctions.sql

package sqlc

import (
	"context"
	"time"
)

const countAuctions = `-- name: CountAuctions :one
SELECT COUNT(*) AS total
FROM auctions
WHERE
    ($1::auction_status IS NULL OR status = $1::auction_status)
    AND ($2::int  IS NULL OR category_id = $2::int)
    AND ($3::bigint IS NULL OR current_price >= $3::bigint)
    AND ($4::bigint IS NULL OR current_price <= $4::bigint)
    AND ($5::int IS NULL OR created_by = $5::int)
    AND (
        $6::text IS NULL 
        OR search_vector @@ websearch_to_tsquery('simple', $6::text)
        OR search_vector @@ websearch_to_tsquery('simple', vn_unaccent($6::text))
    )
`

type CountAuctionsParams struct {
	Status     interface{} `json:"status"`
	CategoryID *int32      `json:"category_id"`
	MinPrice   *int64      `json:"min_price"`
	MaxPrice   *int64      `json:"max_price"`
	OwnerID    *int32      `json:"owner_id"`
	Query      *string     `json:"query"`
}

func (q *Queries) CountAuctions(ctx context.Context, arg CountAuctionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuctions,
		arg.Status,
		arg.CategoryID,
		arg.MinPrice,
		arg.MaxPrice,
		arg.OwnerID,
		arg.Query,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countAuctionsEndingSoon = `-- name: CountAuctionsEndingSoon :one
SELECT COUNT(*) AS total
FROM auctions
WHERE
    ($1::auction_status IS NULL OR status = $1::auction_status)
    AND ($2::int  IS NULL OR category_id = $2::int)
    AND ($3::bigint IS NULL OR current_price >= $3::bigint)
    AND ($4::bigint IS NULL OR current_price <= $4::bigint)
    AND ($5::int IS NULL OR created_by = $5::int)
    AND (
        $6::text IS NULL 
        OR search_vector @@ websearch_to_tsquery('simple', $6::text)
        OR search_vector @@ websearch_to_tsquery('simple', vn_unaccent($6::text))
    )
    AND end_time > NOW()
    AND end_time <= NOW() + interval '24 hours'
`

type CountAuctionsEndingSoonParams struct {
	Status     interface{} `json:"status"`
	CategoryID *int32      `json:"category_id"`
	MinPrice   *int64      `json:"min_price"`
	MaxPrice   *int64      `json:"max_price"`
	OwnerID    *int32      `json:"owner_id"`
	Query      *string     `json:"query"`
}

func (q *Queries) CountAuctionsEndingSoon(ctx context.Context, arg CountAuctionsEndingSoonParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuctionsEndingSoon,
		arg.Status,
		arg.CategoryID,
		arg.MinPrice,
		arg.MaxPrice,
		arg.OwnerID,
		arg.Query,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createAuction = `-- name: CreateAuction :one
INSERT INTO auctions(
    title,
    description,
    category_id,
    start_price,
    current_price,
    min_bid_increment,
    start_time,
    end_time,
    created_by
) VALUES(
    $1, $2, $3, $4, $4, $5, $6, $7, $8
)
RETURNING id, title, description, category_id, start_price, current_price, min_bid_increment, start_time, end_time, status, created_by, winner_id, version, extension_count, max_extensions, created_at, updated_at, search_vector
`

type CreateAuctionParams struct {
	Title           string    `json:"title"`
	Description     *string   `json:"description"`
	CategoryID      *int32    `json:"category_id"`
	StartPrice      int64     `json:"start_price"`
	MinBidIncrement int64     `json:"min_bid_increment"`
	StartTime       time.Time `json:"start_time"`
	EndTime         time.Time `json:"end_time"`
	CreatedBy       int32     `json:"created_by"`
}

func (q *Queries) CreateAuction(ctx context.Context, arg CreateAuctionParams) (Auction, error) {
	row := q.db.QueryRow(ctx, createAuction,
		arg.Title,
		arg.Description,
		arg.CategoryID,
		arg.StartPrice,
		arg.MinBidIncrement,
		arg.StartTime,
		arg.EndTime,
		arg.CreatedBy,
	)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.StartPrice,
		&i.CurrentPrice,
		&i.MinBidIncrement,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedBy,
		&i.WinnerID,
		&i.Version,
		&i.ExtensionCount,
		&i.MaxExtensions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const deleteAuction = `-- name: DeleteAuction :exec
DELETE FROM auctions
WHERE id = $1 AND status = 'PENDING'
`

func (q *Queries) DeleteAuction(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAuction, id)
	return err
}

const getAuctionByID = `-- name: GetAuctionByID :one
SELECT id, title, description, category_id, start_price, current_price, min_bid_increment, start_time, end_time, status, created_by, winner_id, version, extension_count, max_extensions, created_at, updated_at, search_vector
FROM auctions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAuctionByID(ctx context.Context, id int32) (Auction, error) {
	row := q.db.QueryRow(ctx, getAuctionByID, id)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.StartPrice,
		&i.CurrentPrice,
		&i.MinBidIncrement,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedBy,
		&i.WinnerID,
		&i.Version,
		&i.ExtensionCount,
		&i.MaxExtensions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const getAuctionOwner = `-- name: GetAuctionOwner :one
SELECT id, created_by, status
FROM auctions
WHERE id = $1
LIMIT 1
`

type GetAuctionOwnerRow struct {
	ID        int32  `json:"id"`
	CreatedBy int32  `json:"created_by"`
	Status    string `json:"status"`
}

func (q *Queries) GetAuctionOwner(ctx context.Context, id int32) (GetAuctionOwnerRow, error) {
	row := q.db.QueryRow(ctx, getAuctionOwner, id)
	var i GetAuctionOwnerRow
	err := row.Scan(&i.ID, &i.CreatedBy, &i.Status)
	return i, err
}

const listAuctionsEndingSoon = `-- name: ListAuctionsEndingSoon :many
SELECT id, title, description, category_id, start_price, current_price, min_bid_increment, start_time, end_time, status, created_by, winner_id, version, extension_count, max_extensions, created_at, updated_at, search_vector
FROM auctions
WHERE
    ($3::auction_status IS NULL OR status = $3::auction_status)
    AND ($4::int IS NULL OR category_id = $4::int)
    AND ($5::bigint IS NULL OR current_price >= $5::bigint)
    AND ($6::bigint IS NULL OR current_price <= $6::bigint)
    AND ($7::int IS NULL OR created_by = $7::int)
    AND (
        $8::text IS NULL 
        OR search_vector @@ websearch_to_tsquery('simple', $8::text)
        OR search_vector @@ websearch_to_tsquery('simple', vn_unaccent($8::text))
    )
    AND end_time > NOW()
    AND end_time <= NOW() + interval '24 hours'
ORDER BY end_time ASC
LIMIT $1 OFFSET $2
`

type ListAuctionsEndingSoonParams struct {
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	Status     interface{} `json:"status"`
	CategoryID *int32      `json:"category_id"`
	MinPrice   *int64      `json:"min_price"`
	MaxPrice   *int64      `json:"max_price"`
	OwnerID    *int32      `json:"owner_id"`
	Query      *string     `json:"query"`
}

func (q *Queries) ListAuctionsEndingSoon(ctx context.Context, arg ListAuctionsEndingSoonParams) ([]Auction, error) {
	rows, err := q.db.Query(ctx, listAuctionsEndingSoon,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.CategoryID,
		arg.MinPrice,
		arg.MaxPrice,
		arg.OwnerID,
		arg.Query,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Auction{}
	for rows.Next() {
		var i Auction
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CategoryID,
			&i.StartPrice,
			&i.CurrentPrice,
			&i.MinBidIncrement,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.CreatedBy,
			&i.WinnerID,
			&i.Version,
			&i.ExtensionCount,
			&i.MaxExtensions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuctionsNewest = `-- name: ListAuctionsNewest :many
SELECT id, title, description, category_id, start_price, current_price, min_bid_increment, start_time, end_time, status, created_by, winner_id, version, extension_count, max_extensions, created_at, updated_at, search_vector
FROM auctions
WHERE
    ($3::auction_status IS NULL OR status = $3::auction_status)
    AND ($4::int  IS NULL OR category_id = $4::int)
    AND ($5::bigint IS NULL OR current_price >= $5::bigint)
    AND ($6::bigint IS NULL OR current_price <= $6::bigint)
    AND ($7::int IS NULL OR created_by = $7::int)
    AND (
        $8::text IS NULL 
        OR search_vector @@ websearch_to_tsquery('simple', $8::text)
        OR search_vector @@ websearch_to_tsquery('simple', vn_unaccent($8::text))
    )
ORDER BY created_at DESC
LIMIT  $1 OFFSET $2
`

type ListAuctionsNewestParams struct {
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	Status     interface{} `json:"status"`
	CategoryID *int32      `json:"category_id"`
	MinPrice   *int64      `json:"min_price"`
	MaxPrice   *int64      `json:"max_price"`
	OwnerID    *int32      `json:"owner_id"`
	Query      *string     `json:"query"`
}

func (q *Queries) ListAuctionsNewest(ctx context.Context, arg ListAuctionsNewestParams) ([]Auction, error) {
	rows, err := q.db.Query(ctx, listAuctionsNewest,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.CategoryID,
		arg.MinPrice,
		arg.MaxPrice,
		arg.OwnerID,
		arg.Query,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Auction{}
	for rows.Next() {
		var i Auction
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CategoryID,
			&i.StartPrice,
			&i.CurrentPrice,
			&i.MinBidIncrement,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.CreatedBy,
			&i.WinnerID,
			&i.Version,
			&i.ExtensionCount,
			&i.MaxExtensions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuctionsPriceAsc = `-- name: ListAuctionsPriceAsc :many
SELECT id, title, description, category_id, start_price, current_price, min_bid_increment, start_time, end_time, status, created_by, winner_id, version, extension_count, max_extensions, created_at, updated_at, search_vector
FROM auctions
WHERE
    ($3::auction_status IS NULL OR status = $3::auction_status)
    AND ($4::int  IS NULL OR category_id = $4::int)
    AND ($5::bigint IS NULL OR current_price >= $5::bigint)
    AND ($6::bigint IS NULL OR current_price <= $6::bigint)
    AND ($7::int IS NULL OR created_by = $7::int)
    AND (
        $8::text IS NULL 
        OR search_vector @@ websearch_to_tsquery('simple', $8::text)
        OR search_vector @@ websearch_to_tsquery('simple', vn_unaccent($8::text))
    )
ORDER BY current_price ASC
LIMIT  $1 OFFSET $2
`

type ListAuctionsPriceAscParams struct {
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	Status     interface{} `json:"status"`
	CategoryID *int32      `json:"category_id"`
	MinPrice   *int64      `json:"min_price"`
	MaxPrice   *int64      `json:"max_price"`
	OwnerID    *int32      `json:"owner_id"`
	Query      *string     `json:"query"`
}

func (q *Queries) ListAuctionsPriceAsc(ctx context.Context, arg ListAuctionsPriceAscParams) ([]Auction, error) {
	rows, err := q.db.Query(ctx, listAuctionsPriceAsc,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.CategoryID,
		arg.MinPrice,
		arg.MaxPrice,
		arg.OwnerID,
		arg.Query,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Auction{}
	for rows.Next() {
		var i Auction
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CategoryID,
			&i.StartPrice,
			&i.CurrentPrice,
			&i.MinBidIncrement,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.CreatedBy,
			&i.WinnerID,
			&i.Version,
			&i.ExtensionCount,
			&i.MaxExtensions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuctionsPriceDesc = `-- name: ListAuctionsPriceDesc :many
SELECT id, title, description, category_id, start_price, current_price, min_bid_increment, start_time, end_time, status, created_by, winner_id, version, extension_count, max_extensions, created_at, updated_at, search_vector
FROM auctions
WHERE
    ($3::auction_status IS NULL OR status = $3::auction_status)
    AND ($4::int  IS NULL OR category_id = $4::int)
    AND ($5::bigint IS NULL OR current_price >= $5::bigint)
    AND ($6::bigint IS NULL OR current_price <= $6::bigint)
    AND ($7::int IS NULL OR created_by = $7::int)
    AND (
        $8::text IS NULL 
        OR search_vector @@ websearch_to_tsquery('simple', $8::text)
        OR search_vector @@ websearch_to_tsquery('simple', vn_unaccent($8::text))
    )
ORDER BY current_price DESC NULLS LAST, id DESC
LIMIT  $1 OFFSET $2
`

type ListAuctionsPriceDescParams struct {
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	Status     interface{} `json:"status"`
	CategoryID *int32      `json:"category_id"`
	MinPrice   *int64      `json:"min_price"`
	MaxPrice   *int64      `json:"max_price"`
	OwnerID    *int32      `json:"owner_id"`
	Query      *string     `json:"query"`
}

func (q *Queries) ListAuctionsPriceDesc(ctx context.Context, arg ListAuctionsPriceDescParams) ([]Auction, error) {
	rows, err := q.db.Query(ctx, listAuctionsPriceDesc,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.CategoryID,
		arg.MinPrice,
		arg.MaxPrice,
		arg.OwnerID,
		arg.Query,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Auction{}
	for rows.Next() {
		var i Auction
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CategoryID,
			&i.StartPrice,
			&i.CurrentPrice,
			&i.MinBidIncrement,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.CreatedBy,
			&i.WinnerID,
			&i.Version,
			&i.ExtensionCount,
			&i.MaxExtensions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuctionsRelevance = `-- name: ListAuctionsRelevance :many
SELECT id, title, description, category_id, start_price, current_price, min_bid_increment, start_time, end_time, status, created_by, winner_id, version, extension_count, max_extensions, created_at, updated_at, search_vector
FROM auctions
WHERE
    ($3::auction_status IS NULL OR status = $3::auction_status)
    AND ($4::int  IS NULL OR category_id = $4::int)
    AND ($5::bigint IS NULL OR current_price >= $5::bigint)
    AND ($6::bigint IS NULL OR current_price <= $6::bigint)
    AND ($7::int IS NULL OR created_by = $7::int)
    AND (
        $8::text IS NULL 
        OR search_vector @@ websearch_to_tsquery('simple', $8::text)
        OR search_vector @@ websearch_to_tsquery('simple', vn_unaccent($8::text))
    )
ORDER BY 
    (CASE 
        WHEN $8::text IS NOT NULL THEN 
            ts_rank(search_vector, websearch_to_tsquery('simple', $8::text)) +
            ts_rank(search_vector, websearch_to_tsquery('simple', vn_unaccent($8::text)))
        ELSE 0 
    END) DESC,
    created_at DESC
LIMIT  $1 OFFSET $2
`

type ListAuctionsRelevanceParams struct {
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	Status     interface{} `json:"status"`
	CategoryID *int32      `json:"category_id"`
	MinPrice   *int64      `json:"min_price"`
	MaxPrice   *int64      `json:"max_price"`
	OwnerID    *int32      `json:"owner_id"`
	Query      *string     `json:"query"`
}

func (q *Queries) ListAuctionsRelevance(ctx context.Context, arg ListAuctionsRelevanceParams) ([]Auction, error) {
	rows, err := q.db.Query(ctx, listAuctionsRelevance,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.CategoryID,
		arg.MinPrice,
		arg.MaxPrice,
		arg.OwnerID,
		arg.Query,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Auction{}
	for rows.Next() {
		var i Auction
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CategoryID,
			&i.StartPrice,
			&i.CurrentPrice,
			&i.MinBidIncrement,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.CreatedBy,
			&i.WinnerID,
			&i.Version,
			&i.ExtensionCount,
			&i.MaxExtensions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoverImagesByAuctionIDs = `-- name: ListCoverImagesByAuctionIDs :many
SELECT DISTINCT ON (auction_id)
    id, auction_id, url, filename, size_bytes, mime_type, sort_order, is_primary, created_at
FROM auction_images
WHERE auction_id = ANY($1::int[])
ORDER BY auction_id, is_primary DESC, sort_order ASC, id ASC
`

func (q *Queries) ListCoverImagesByAuctionIDs(ctx context.Context, dollar_1 []int32) ([]AuctionImage, error) {
	rows, err := q.db.Query(ctx, listCoverImagesByAuctionIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuctionImage{}
	for rows.Next() {
		var i AuctionImage
		if err := rows.Scan(
			&i.ID,
			&i.AuctionID,
			&i.Url,
			&i.Filename,
			&i.SizeBytes,
			&i.MimeType,
			&i.SortOrder,
			&i.IsPrimary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuction = `-- name: UpdateAuction :one
UPDATE auctions
SET
    title = COALESCE($2::varchar, title),
    description = COALESCE($3::text, description),
    category_id = COALESCE($4::int, category_id),
    start_price = COALESCE($5::bigint, start_price),
    min_bid_increment = COALESCE($6::bigint, min_bid_increment),
    start_time = COALESCE($7::timestamptz, start_time),
    end_time = COALESCE($8::timestamptz, end_time),
    current_price = COALESCE($5::bigint, current_price)
WHERE id = $1 AND status = 'PENDING'
RETURNING id, title, description, category_id, start_price, current_price, min_bid_increment, start_time, end_time, status, created_by, winner_id, version, extension_count, max_extensions, created_at, updated_at, search_vector
`

type UpdateAuctionParams struct {
	ID              int32      `json:"id"`
	Title           *string    `json:"title"`
	Description     *string    `json:"description"`
	CategoryID      *int32     `json:"category_id"`
	StartPrice      *int64     `json:"start_price"`
	MinBidIncrement *int64     `json:"min_bid_increment"`
	StartTime       *time.Time `json:"start_time"`
	EndTime         *time.Time `json:"end_time"`
}

func (q *Queries) UpdateAuction(ctx context.Context, arg UpdateAuctionParams) (Auction, error) {
	row := q.db.QueryRow(ctx, updateAuction,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.CategoryID,
		arg.StartPrice,
		arg.MinBidIncrement,
		arg.StartTime,
		arg.EndTime,
	)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.StartPrice,
		&i.CurrentPrice,
		&i.MinBidIncrement,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedBy,
		&i.WinnerID,
		&i.Version,
		&i.ExtensionCount,
		&i.MaxExtensions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}
