// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auctions.sql

package sqlc

import (
	"context"
	"time"
)

const createAuction = `-- name: CreateAuction :one
INSERT INTO auctions(
    title,
    description,
    category_id,
    start_price,
    current_price,
    min_bid_increment,
    start_time,
    end_time,
    created_by
) VALUES(
    $1, $2, $3, $4, $4, $5, $6, $7, $8
)
RETURNING id, title, description, category_id, start_price, current_price, min_bid_increment, start_time, end_time, status, created_by, winner_id, version, extension_count, max_extensions, created_at, updated_at
`

type CreateAuctionParams struct {
	Title           string    `json:"title"`
	Description     *string   `json:"description"`
	CategoryID      *int32    `json:"category_id"`
	StartPrice      int64     `json:"start_price"`
	MinBidIncrement int64     `json:"min_bid_increment"`
	StartTime       time.Time `json:"start_time"`
	EndTime         time.Time `json:"end_time"`
	CreatedBy       int32     `json:"created_by"`
}

func (q *Queries) CreateAuction(ctx context.Context, arg CreateAuctionParams) (Auction, error) {
	row := q.db.QueryRow(ctx, createAuction,
		arg.Title,
		arg.Description,
		arg.CategoryID,
		arg.StartPrice,
		arg.MinBidIncrement,
		arg.StartTime,
		arg.EndTime,
		arg.CreatedBy,
	)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.StartPrice,
		&i.CurrentPrice,
		&i.MinBidIncrement,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedBy,
		&i.WinnerID,
		&i.Version,
		&i.ExtensionCount,
		&i.MaxExtensions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActionByID = `-- name: GetActionByID :one
SELECT id, title, description, category_id, start_price, current_price, min_bid_increment, start_time, end_time, status, created_by, winner_id, version, extension_count, max_extensions, created_at, updated_at
FROM auctions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetActionByID(ctx context.Context, id int32) (Auction, error) {
	row := q.db.QueryRow(ctx, getActionByID, id)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.StartPrice,
		&i.CurrentPrice,
		&i.MinBidIncrement,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedBy,
		&i.WinnerID,
		&i.Version,
		&i.ExtensionCount,
		&i.MaxExtensions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuctionOwner = `-- name: GetAuctionOwner :one
SELECT id, created_by, status
FROM auctions
WHERE id = $1
LIMIT 1
`

type GetAuctionOwnerRow struct {
	ID        int32  `json:"id"`
	CreatedBy int32  `json:"created_by"`
	Status    string `json:"status"`
}

func (q *Queries) GetAuctionOwner(ctx context.Context, id int32) (GetAuctionOwnerRow, error) {
	row := q.db.QueryRow(ctx, getAuctionOwner, id)
	var i GetAuctionOwnerRow
	err := row.Scan(&i.ID, &i.CreatedBy, &i.Status)
	return i, err
}
