// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bids.sql

package sqlc

import (
	"context"
	"time"
)

const activateAuctions = `-- name: ActivateAuctions :many
UPDATE auctions
SET status = 'ACTIVE'
WHERE status = 'PENDING' AND start_time <= NOW()
RETURNING id
`

func (q *Queries) ActivateAuctions(ctx context.Context) ([]int32, error) {
	rows, err := q.db.Query(ctx, activateAuctions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countBidsByAuction = `-- name: CountBidsByAuction :one
SELECT COUNT(*)::bigint AS total FROM bids WHERE auction_id = $1
`

func (q *Queries) CountBidsByAuction(ctx context.Context, auctionID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countBidsByAuction, auctionID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const endAuctions = `-- name: EndAuctions :many
UPDATE auctions a
SET
    status = 'ENDED',
    winner_id = (
        SELECT user_id FROM bids
        WHERE auction_id = a.id
        ORDER BY auction_version DESC
        LIMIT 1
    )
WHERE a.status = 'ACTIVE' AND a.end_time <= NOW()
RETURNING a.id, a.title, a.current_price, a.winner_id
`

type EndAuctionsRow struct {
	ID           int32  `json:"id"`
	Title        string `json:"title"`
	CurrentPrice int64  `json:"current_price"`
	WinnerID     *int32 `json:"winner_id"`
}

func (q *Queries) EndAuctions(ctx context.Context) ([]EndAuctionsRow, error) {
	rows, err := q.db.Query(ctx, endAuctions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EndAuctionsRow{}
	for rows.Next() {
		var i EndAuctionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CurrentPrice,
			&i.WinnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuctionForActor = `-- name: GetAuctionForActor :one
SELECT id, current_price, version, extension_count, max_extensions, created_by, status, min_bid_increment, start_time, end_time
FROM auctions
WHERE id = $1
`

type GetAuctionForActorRow struct {
	ID              int32     `json:"id"`
	CurrentPrice    int64     `json:"current_price"`
	Version         int64     `json:"version"`
	ExtensionCount  int32     `json:"extension_count"`
	MaxExtensions   int32     `json:"max_extensions"`
	CreatedBy       int32     `json:"created_by"`
	Status          string    `json:"status"`
	MinBidIncrement int64     `json:"min_bid_increment"`
	StartTime       time.Time `json:"start_time"`
	EndTime         time.Time `json:"end_time"`
}

func (q *Queries) GetAuctionForActor(ctx context.Context, id int32) (GetAuctionForActorRow, error) {
	row := q.db.QueryRow(ctx, getAuctionForActor, id)
	var i GetAuctionForActorRow
	err := row.Scan(
		&i.ID,
		&i.CurrentPrice,
		&i.Version,
		&i.ExtensionCount,
		&i.MaxExtensions,
		&i.CreatedBy,
		&i.Status,
		&i.MinBidIncrement,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const insertBid = `-- name: InsertBid :one
INSERT INTO bids (auction_id, user_id, bid_price, auction_version)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at
`

type InsertBidParams struct {
	AuctionID      int32 `json:"auction_id"`
	UserID         int32 `json:"user_id"`
	BidPrice       int64 `json:"bid_price"`
	AuctionVersion int64 `json:"auction_version"`
}

type InsertBidRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) InsertBid(ctx context.Context, arg InsertBidParams) (InsertBidRow, error) {
	row := q.db.QueryRow(ctx, insertBid,
		arg.AuctionID,
		arg.UserID,
		arg.BidPrice,
		arg.AuctionVersion,
	)
	var i InsertBidRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listBidsByAuction = `-- name: ListBidsByAuction :many
SELECT b.id, b.bid_price, b.auction_version, b.created_at, u.full_name AS bidder_name
FROM bids b
JOIN users u ON u.user_id = b.user_id
WHERE b.auction_id = $1
ORDER BY b.auction_version DESC
LIMIT $2 OFFSET $3
`

type ListBidsByAuctionParams struct {
	AuctionID int32 `json:"auction_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

type ListBidsByAuctionRow struct {
	ID             int64     `json:"id"`
	BidPrice       int64     `json:"bid_price"`
	AuctionVersion int64     `json:"auction_version"`
	CreatedAt      time.Time `json:"created_at"`
	BidderName     string    `json:"bidder_name"`
}

func (q *Queries) ListBidsByAuction(ctx context.Context, arg ListBidsByAuctionParams) ([]ListBidsByAuctionRow, error) {
	rows, err := q.db.Query(ctx, listBidsByAuction, arg.AuctionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBidsByAuctionRow{}
	for rows.Next() {
		var i ListBidsByAuctionRow
		if err := rows.Scan(
			&i.ID,
			&i.BidPrice,
			&i.AuctionVersion,
			&i.CreatedAt,
			&i.BidderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const placeBid = `-- name: PlaceBid :one
UPDATE auctions
SET
    current_price = $1,
    version = version +1,
    extension_count = CASE
        WHEN end_time <= NOW() + interval '10 seconds'
            AND extension_count < max_extensions
        THEN extension_count +1
        ELSE extension_count
    END,
    end_time = CASE
        WHEN end_time <= NOW() + interval '10 seconds'
            AND extension_count < max_extensions
        THEN end_time + INTERVAL '10 seconds'
        ELSE end_time
    END
WHERE id = $2
    AND status = 'ACTIVE'
    AND start_time <= NOW()
    AND end_time >= NOW()
    AND $1 >= current_price + min_bid_increment
    AND $3 != created_by
RETURNING version, end_time, extension_count, current_price
`

type PlaceBidParams struct {
	CurrentPrice int64 `json:"current_price"`
	ID           int32 `json:"id"`
	CreatedBy    int32 `json:"created_by"`
}

type PlaceBidRow struct {
	Version        int64     `json:"version"`
	EndTime        time.Time `json:"end_time"`
	ExtensionCount int32     `json:"extension_count"`
	CurrentPrice   int64     `json:"current_price"`
}

func (q *Queries) PlaceBid(ctx context.Context, arg PlaceBidParams) (PlaceBidRow, error) {
	row := q.db.QueryRow(ctx, placeBid, arg.CurrentPrice, arg.ID, arg.CreatedBy)
	var i PlaceBidRow
	err := row.Scan(
		&i.Version,
		&i.EndTime,
		&i.ExtensionCount,
		&i.CurrentPrice,
	)
	return i, err
}
