// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package sqlc

import (
	"context"
)

const categoryExists = `-- name: CategoryExists :one
SELECT EXISTS(
    SELECT 1 FROM categories WHERE id = $1
) AS exists
`

func (q *Queries) CategoryExists(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, categoryExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, slug, sort_order
FROM categories
WHERE id = $1
LIMIT 1
`

type GetCategoryByIDRow struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) GetCategoryByID(ctx context.Context, id int32) (GetCategoryByIDRow, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i GetCategoryByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SortOrder,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug, sort_order
FROM categories
ORDER BY sort_order ASC, id ASC
`

type ListCategoriesRow struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) ListCategories(ctx context.Context) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesRow{}
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
