// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Auction struct {
	ID              int32     `json:"id"`
	Title           string    `json:"title"`
	Description     *string   `json:"description"`
	CategoryID      *int32    `json:"category_id"`
	StartPrice      int64     `json:"start_price"`
	CurrentPrice    int64     `json:"current_price"`
	MinBidIncrement int64     `json:"min_bid_increment"`
	StartTime       time.Time `json:"start_time"`
	EndTime         time.Time `json:"end_time"`
	Status          string    `json:"status"`
	CreatedBy       int32     `json:"created_by"`
	WinnerID        *int32    `json:"winner_id"`
	Version         int64     `json:"version"`
	ExtensionCount  int32     `json:"extension_count"`
	MaxExtensions   int32     `json:"max_extensions"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type AuctionImage struct {
	ID        int32     `json:"id"`
	AuctionID int32     `json:"auction_id"`
	Url       string    `json:"url"`
	Filename  string    `json:"filename"`
	SizeBytes int32     `json:"size_bytes"`
	MimeType  string    `json:"mime_type"`
	SortOrder int32     `json:"sort_order"`
	IsPrimary bool      `json:"is_primary"`
	CreatedAt time.Time `json:"created_at"`
}

type Bid struct {
	ID             int64     `json:"id"`
	AuctionID      int32     `json:"auction_id"`
	UserID         int32     `json:"user_id"`
	BidPrice       int64     `json:"bid_price"`
	AuctionVersion int64     `json:"auction_version"`
	CreatedAt      time.Time `json:"created_at"`
}

type Category struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	SortOrder int32     `json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	UserID       int32     `json:"user_id"`
	UserUuid     uuid.UUID `json:"user_uuid"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	FullName     string    `json:"full_name"`
	AvatarUrl    *string   `json:"avatar_url"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
