CREATE TABLE IF NOT EXISTS categories(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO categories (name, slug, sort_order) VALUES
    ('Điện tử',      'dien-tu',      1),
    ('Thời trang',   'thoi-trang',   2),
    ('Xe cộ',        'xe-co',        3),
    ('Bất động sản', 'bat-dong-san', 4),
    ('Nghệ thuật',   'nghe-thuat',   5),
    ('Đồ cổ',        'do-co',        6)
ON CONFLICT (slug) DO NOTHING;

