CREATE TABLE IF NOT EXISTS auction_images (
    id         INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auction_id INT          NOT NULL REFERENCES auctions(id) ON DELETE CASCADE,
    url        VARCHAR(500) NOT NULL,
    filename   VARCHAR(255) NOT NULL,
    size_bytes INT          NOT NULL,
    mime_type  VARCHAR(50)  NOT NULL,
    sort_order INT          NOT NULL DEFAULT 0,
    is_primary BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE        INDEX IF NOT EXISTS idx_images_auction ON auction_images(auction_id, sort_order);
CREATE UNIQUE INDEX IF NOT EXISTS idx_images_primary ON auction_images(auction_id) WHERE is_primary = TRUE;
