CREATE TABLE IF NOT EXISTS bids(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auction_id INT NOT NULL REFERENCES auctions(id) ON DELETE RESTRICT,
    user_id INT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    bid_price BIGINT NOT NULL,
    auction_version BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_bid_price CHECK (bid_price > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_bids_order ON bids(auction_id, auction_version);
CREATE INDEX IF NOT EXISTS idx_bids_user ON bids(user_id, created_at DESC);